services:
  app:
    image: react-typescript-example:latest
    build:
      context:      .
      dockerfile:   Dockerfile
      extra_hosts:
      - "npm-registry.srv.axiomptk:10.2.3.4"
      - "npm-registry.srv.axiomptk:10.2.10.2"
    ports:
    - "8787:80"
    # profiles:
    #   - app

  storybook:
    image: react-typescript-example-storybook:latest
    build:
      context:      .
      dockerfile:   Dockerfile.storybook
      extra_hosts:
      - "npm-registry.srv.axiomptk:10.2.3.4"
      - "npm-registry.srv.axiomptk:10.2.10.2"
    ports:
    - "8888:80"
